{% set name = "py2app" %}
{% set version = "0.28.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c7b1233e2c896c0c4b6a8946fb0cee248866129c3b6db390ffa568a8325e734f
  patches:
    - distutils.patch  # [python_impl == 'pypy']

build:
  skip: true  # [not osx]
  number: 0
  entry_points:
    - py2applet = py2app.script_py2applet:main
  missing_dso_whitelist:
    - '*/libgcc_s.1.dylib'

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - altgraph >=0.16
    - macholib >=1.16
    - modulegraph >=0.17
    - pip
    - python
    - setuptools
  run:
    - altgraph >=0.16
    - macholib >=1.16
    - modulegraph >=0.17
    - python
    - setuptools

test:
  imports:
    - py2app
    - py2app.apptemplate
    - py2app.bootstrap
    - py2app.bundletemplate
    - py2app.converters
    - py2app.recipes
    - py2app.recipes.PIL
  commands:
    - py2applet

about:
  home: https://github.com/ronaldoussoren/py2app
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: |
    py2app is a Python setuptools command which will allow you to make
    standalone Mac OS X application bundles and plugins from Python scripts.
    py2app is similar in purpose and design to py2exe for Windows.
    py2app must be used on OSX to build applications, it cannot create Mac
    applications on other platforms.
  doc_url: https://py2app.readthedocs.io/en/latest/
  dev_url: https://github.com/ronaldoussoren/py2app

extra:
  recipe-maintainers:
    - bkpoon
