{% set name = "py2app" %}
{% set version = "0.22" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0ec29109338cb7c5340457aa6df972904d0d00533e8ab4107b9e00fe1da5d300

build:
  skip: true  # [not osx]
  number: 2
  entry_points:
    - py2applet = py2app.script_py2applet:main
  missing_dso_whitelist:
    - '*/libgcc_s.1.dylib'

requirements:
  host:
    - pip
    - python
    - unittest2
  run:
    - altgraph >=0.16
    - macholib >=1.11
    - modulegraph >=0.17
    - python

test:
  imports:
    - py2app
    - py2app.apptemplate
    - py2app.bootstrap
    - py2app.bundletemplate
    - py2app.converters
    - py2app.recipes
    - py2app.recipes.PIL
  commands:
    - pip check
    - py2applet --help
  requires:
    - pip
    - pyobjc-core

about:
  home: http://github.com/ronaldoussoren/py2app
  summary: Create standalone Mac OS X applications with Python
  doc_url: https://py2app.readthedocs.io/en/latest/
  license: MIT
  license_file: LICENSE.txt
  summary: |
    py2app is a Python setuptools command which will allow you to make
    standalone Mac OS X application bundles and plugins from Python scripts.
    py2app is similar in purpose and design to py2exe for Windows.
    py2app must be used on OSX to build applications, it cannot create Mac
    applications on other platforms.
  dev_url: https://github.com/ronaldoussoren/py2app

extra:
  recipe-maintainers:
    - bkpoon
